### ISSUE TITLE
Can't upgrade plugin to 4.0.1 after upgrading redmine to 6.0.2

### ISSUE THREAD

**Issue by mrPsycho** [danmunn/redmine_dmsf#1580]
Hello,

i was using this plugin for a while, and recently updated redmine. 
as well tried to update plugin, but failing with:
```
redmine@devcenter:~/redmine$ RAILS_ENV=production bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf
rake aborted!
NameError: undefined local variable or method `unloadable' for Redmine::Notifiable:Class (NameError)

          unloadable
          ^^^^^^^^^^
/home/redmine/redmine/plugins/redmine_dmsf/patches/notifiable_ru_patch.rb:29:in `block in included'
/home/redmine/redmine/plugins/redmine_dmsf/patches/notifiable_ru_patch.rb:28:in `class_eval'
/home/redmine/redmine/plugins/redmine_dmsf/patches/notifiable_ru_patch.rb:28:in `included'
/home/redmine/redmine/plugins/redmine_dmsf/patches/notifiable_ru_patch.rb:54:in `include'
/home/redmine/redmine/plugins/redmine_dmsf/patches/notifiable_ru_patch.rb:54:in `<top (required)>'
<internal:/home/redmine/.rbenv/versions/3.2.6/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/home/redmine/.rbenv/versions/3.2.6/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/home/redmine/redmine/plugins/redmine_dmsf/lib/redmine_dmsf.rb:258:in `<top (required)>'
<internal:/home/redmine/.rbenv/versions/3.2.6/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/home/redmine/.rbenv/versions/3.2.6/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/home/redmine/redmine/plugins/redmine_dmsf/after_init.rb:23:in `<top (required)>'
/home/redmine/redmine/plugins/redmine_dmsf/init.rb:73:in `require_relative'
/home/redmine/redmine/plugins/redmine_dmsf/init.rb:73:in `<top (required)>'
/home/redmine/redmine/lib/redmine/plugin_loader.rb:31:in `load'
/home/redmine/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/home/redmine/redmine/lib/redmine/plugin_loader.rb:61:in `each'
/home/redmine/redmine/lib/redmine/plugin_loader.rb:61:in `block in load'
/home/redmine/redmine/config/environment.rb:16:in `<top (required)>'
<internal:/home/redmine/.rbenv/versions/3.2.6/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/home/redmine/.rbenv/versions/3.2.6/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/home/redmine/.rbenv/versions/3.2.6/bin/bundle:25:in `load'
/home/redmine/.rbenv/versions/3.2.6/bin/bundle:25:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by albenik85** [comment]
Just faced the same issue. It can be resolved by removing the "unloadable" method on redmine_dmsf/patches/notifiable_ru_patch.rb

**Comment by picman** [comment]
Thank you for reporting that. Fixed.
