### ISSUE TITLE
Error 500 on Project Settings open

### ISSUE THREAD

**Issue by danaivehr** [danmunn/redmine_dmsf#845]
Opening project settings causes error 500 with log

```
Completed 500 Internal Server Error in 3297ms (ActiveRecord: 8.4ms)

ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x007fbe2670a328>:0x007fbe0f61e2f0>
Did you mean?  project_settings_tabs_without_banner):
    1: <h2><%=l(:label_settings)%></h2>
    2: 
    3: <%= render_tabs project_settings_tabs %>
    4: 
    5: <% html_title(l(:label_settings)) -%>
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in `project_settings_tabs'
  plugins/redmine_issue_templates/lib/issue_templates/projects_helper_patch.rb:16:in `project_settings_tabs_with_issue_templates'
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in `project_settings_tabs'
  app/views/projects/settings.html.erb:3:in `_eebb472fc86cf1d62785ef175f325454'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'

```

Replacing `project_settings_tabs` with `project_settings_tabs_without_banner` works well.

Redmine 3.4.2
DMSF 1.6.1
Ruby 2.3.4
Rails 4.2.8

**Comment by picman** [comment]
It's a conflict with another plugin overriding the same method. Please see IMPORTANT in [CHANGELOG.md](https://github.com/danmunn/redmine_dmsf/blob/master/CHANGELOG.md).

**Comment by danaivehr** [comment]
Thanks, i see.

**Comment by fabricerobin** [comment]
Hi,
How is it possible to fix this ? We have multiple conflict with other plugins...
Regards

**Comment by picman** [comment]
Try the following modification of _plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb_:
```ruby
44 - RedmineExtensions::PatchManager.register_concern_patch 'ProjectsHelper',
45 -    'RedmineDmsf::Patches::ProjectHelperPatch', prepend: true
44 + ProjectsHelper.send(:prepend, RedmineDmsf::Patches::ProjectTabsExtended)
```

**Comment by FragDoc** [comment]
I re-wrote the file based on another plugin and fixed my issue: _plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:_

Should be able to replace the file with the attached file:
[projects_helper_patch.zip](https://github.com/danmunn/redmine_dmsf/files/1916963/projects_helper_patch.zip)

_Disclaimer: I'm not a Ruby developer and only done a few tweaks._

DMSF is a great plugin, thank you!

**Comment by picman** [comment]
You're using `alias_method_chain` which is deprecated. The aim of DMSF 1.6.1 was to get rid of `alias_method_chain`. So, it's not bad workaround but it's still needed to find a better solution.

**Comment by fabricerobin** [comment]
@picman, I tried your suggestion without success.

**Comment by dinya** [comment]
@picman,

Is FragDoc's recipe is fully correct to use in "production" with current master (1.6.1). At least while the solution is not found?

**Comment by picman** [comment]
Yes.

**Comment by tofi86** [comment]
As @fabricerobin stated, I wasn't able to apply the patch by @FragDoc. Doesn't work.

Log shows still errors when trying to access settings page:

```
  plugins/redmine_checklists/lib/redmine_checklists/patches/projects_helper_patch.rb:36:in `project_settings_tabs_with_checklists'
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in `project_settings_tabs'
```

Bad decision changing that plugin behaviour. Have to revert to 1.6.0 for all instances.

**Comment by tofi86** [comment]
And after a git revert to tag `v1.6.0` I get this error:

```
  Rendered plugins/redmine_dmsf/app/views/dmsf_state/_user_pref.html.erb (34.5ms)
  Rendered common/_tabs.html.erb (1290.3ms)
  Rendered projects/settings.html.erb within layouts/base (1355.2ms)
Completed 500 Internal Server Error in 2255ms (ActiveRecord: 66.6ms)

ActionView::Template::Error (undefined method `title_format' for #<Member:0x007f93a4cce338>):
    21: <% member = @project.members.where(:user_id => User.current.id).first %>
    22: <% if member %>
    23:   <% mail_notification = member.dmsf_mail_notification %>
    24:   <% title_format = member.title_format %>
    25: <% end %>
    26:
    27: <%= form_tag(dmsf_user_pref_save_path(@project)) do %>
  plugins/redmine_dmsf/app/views/dmsf_state/_user_pref.html.erb:24:in `_72847eff85c246125b6c170d54805c6c'
  app/views/common/_tabs.html.erb:17:in `block in _8a3faa1218db40d735dc96f5d977a5fd'
  app/views/common/_tabs.html.erb:16:in `each'
  app/views/common/_tabs.html.erb:16:in `_8a3faa1218db40d735dc96f5d977a5fd'
```

Seems to be completely broken now, glad it's just my dev environment.

Sorry @dinya, at the moment I'm not able to implement your lightbox feature request from https://github.com/paginagmbh/redmine_lightbox2/issues/40#issuecomment-382665116

**Comment by fabricerobin** [comment]
It is because you have to downgrade the db before downgrading dmsf to 1.6.0
:

bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf
> VERSION=20171110155901 RAILS_ENV=production


2018-04-20 15:52 GMT+02:00 Tobias Fischer <notifications@github.com>:

**Comment by tofi86** [comment]
@fabricerobin thanks, that worked!

**Comment by dinya** [comment]
@tofi86, try to update ``plugins/redmine_checklists`` if you use https://www.redmineup.com/pages/plugins/checklists. Updated plugin works well with 1.6.1 with @FragDoc recipe in my instance.

**Comment by perryk** [comment]
Just as a bit of a note, this looks to conflict with the Redmine Messenger plugin also. https://github.com/alphanodes/redmine_messenger

The patch above by @FragDoc works around this and I can open project settings again now.

Cheers.

**Comment by dinya** [comment]
@picman 

Error again:

```
Completed 500 Internal Server Error in 569ms (ActiveRecord: 51.3ms)

ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x007f8c030c01e8>:0x007f8c03375c08>
Did you mean?  project_issues_path):
    1: <h2><%=l(:label_settings)%></h2>
    2:
    3: <%= render_tabs project_settings_tabs %>
    4:
    5: <% html_title(l(:label_settings)) -%>
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in `project_settings_tabs'
  plugins/redmine_wiki_extensions/lib/wiki_extensions_projects_helper_patch.rb:35:in `project_settings_tabs_with_wiki_extensions'
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in `project_settings_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___499924262875946318_70119662637640'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'
```

**Comment by picman** [comment]
I'm afraid that the present and future versions of DMSF aren't and won't be compatible with plugins which still use deprecated method `alias_method_chain`.

**Comment by tofi86** [comment]
> I'm afraid that the present and future versions of DMSF aren't and won't be compatible with plugins which still use deprecated method `alias_method_chain`

Wow, that's a bold statement! There's many plugins which don't get updates that often and everyone will be stuck with DMSF 1.6.0

I for myself may update some of my own plugins, but there are so many others!
For the moment I have announced a blocker for updating dmsf plugin internally at our company.

**Comment by Vanav** [comment]
I had to downgrade to 1.6.0. Conflicting plugins in my case:
[redmine_contacts_helpdesk](https://www.redmineup.com/pages/plugins/helpdesk)
[redmine_issue_templates](https://github.com/akiko-pusu/redmine_issue_templates)

**Comment by majkinetor** [comment]
Conflict in my case with [Redminecrm HelpDesk](https://www.redmineup.com/pages/plugins/helpdesk) plugin. I reported to their support.

**Comment by sruttloff** [comment]
I had the same problem with DMSF and finance plugin.
My versions:
Redmine 3.1.1
DMSF 1.6.1
Finance 2.1.7

I have change the file /plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb

#RedmineExtensions::PatchManager.register_helper_patch 'ProjectsHelper',
#    'RedmineDmsf::Patches::ProjectHelperPatch', prepend: true
ProjectsController.send :helper, RedmineDmsf::Patches::ProjectHelperPatch

I'm not sure if it works in newer Redmine versions too.
