### ISSUE TITLE
Can't open settings after upgrade to v3.0.6

### ISSUE THREAD

**Issue by inpos** [danmunn/redmine_dmsf#1404]
Hi!
Trying to open the plugin settings or project settings (with enabled plugin) raises internal error.
```
App 1929436 stdout:   
App 1929436 stdout: ActionView::Template::Error (undefined method `only_public' for #<Class:0x0000563eddc59b90>):
App 1929436 stdout:     170: <p>
App 1929436 stdout:     171:   <%= content_tag :label, l(:label_default_query) %>
App 1929436 stdout:     172:   <% options = [[l(:label_none), nil]] %>
App 1929436 stdout:     173:   <% options.concat DmsfQuery.only_public.where(project_id: nil).pluck(:name, :id) %>
App 1929436 stdout:     174:   <%= select_tag 'settings[dmsf_default_query]',
App 1929436 stdout:     175:        options_for_select(options, selected: @settings['dmsf_default_query']) %>
App 1929436 stdout:     176: </p>
App 1929436 stdout:   
App 1929436 stdout: plugins/redmine_dmsf/app/views/settings/_dmsf_settings.html.erb:173:in `_plugins_redmine_dmsf_app_views_settings__dmsf_settings_html_erb___3128994967766817992_277080'
App 1929436 stdout: app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb__2093258515329231057_277060'
App 1929436 stdout: app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb__2093258515329231057_277060'
App 1929436 stdout: lib/redmine/sudo_mode.rb:61:in `sudo_mode'
App 1929436 stdout: plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:54:in `call'
```

**Comment by picman** [comment]
No more support for the Russians, sorry.
