### ISSUE TITLE
Can't access to WebDAV root directory

### ISSUE THREAD

**Issue by ocanam** [danmunn/redmine_dmsf#427]
### The setup ###
```
Debian 8.1 amd64
Apache 2.4 with Passenger

Environment:
  Redmine version                3.0.4.stable.14445
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Git                            2.1.4
  Filesystem                     
  Xitolite                       2.1.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.3
  redmine_ckeditor               1.1.0
  redmine_default_members        1.0.0
  redmine_dmsf                   1.5.2
  redmine_embedded               0.0.2
  redmine_git_hosting            1.1.1
  redmine_jenkins                1.0.1
  redmine_knowledgebase          3.0.7
  redmine_lightbox2              0.2.2
  redmine_per_project_formatting 0.0.4
```

### The problem ###
After updating the plugin from v1.5.1 to 1.5.2e, accessing to the webdav root directory produce an `Internal Error 500`

```
Started GET "/dmsf/webdav/" for 85.27.78.235 at 2015-08-03 08:40:40 +0200

NoMethodError (undefined method `<<' for nil:NilClass):
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/index_resource.rb:36:in `block in children'
  activerecord (4.2.3) lib/active_record/relation/delegation.rb:46:in `each'
  activerecord (4.2.3) lib/active_record/relation/delegation.rb:46:in `each'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/index_resource.rb:36:in `children'
  dav4rack (0.3.0) lib/dav4rack/resource.rb:116:in `method_missing'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/base_resource.rb:66:in `html_display'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/index_resource.rb:80:in `get'
  dav4rack (0.3.0) lib/dav4rack/resource.rb:116:in `method_missing'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/resource_proxy.rb:101:in `get'
  dav4rack (0.3.0) lib/dav4rack/resource.rb:116:in `method_missing'
  dav4rack (0.3.0) lib/dav4rack/controller.rb:78:in `get'
  dav4rack (0.3.0) lib/dav4rack/handler.rb:30:in `call'
  actionpack (4.2.3) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
  rack-raw-upload (1.1.1) lib/rack/raw_upload.rb:18:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack-xml_parser (1.0.2) lib/action_dispatch/xml_params_parser.rb:16:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/application.rb:165:in `call'
  railties (4.2.3) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.3) lib/rails/railtie.rb:194:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
```

Once inside the directory of a project, all seems ok (from web browser or using Windows 8 buitin WebDAV client).
```
Started GET "/dmsf/webdav/sandbox" for 85.27.78.235 at 2015-08-03 08:52:21 +0200
Started GET "/dmsf/webdav/sandbox/test_folder" for 85.27.78.235 at 2015-08-03 08:53:35 +0200
Started GET "/dmsf/webdav/sandbox/hello.txt" for 85.27.78.235 at 2015-08-03 08:53:43 +0200
```

**Comment by picman** [comment]
Fixed. Thank you for the bug report.

**Comment by ocanam** [comment]
Great! Thank you for this very good and always better plugin.
