### ISSUE TITLE
unable to upload files with ruby > ruby-2.0.0-p598

### ISSUE THREAD

**Issue by morph027** [danmunn/redmine_dmsf#494]
```
Started POST "/projects/playground/dmsf/upload/commit?folder_id=93" for ...
Processing by DmsfUploadController#commit_files as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"...", "commited_files"=>{"1"=>{"disk_filename"=>"160107095938_Template-Plain.docx", "title"=>"Template-Plain", "name"=>"Template-Plain.docx", "description"=>"", "version"=>"1", "custom_version_major"=>"2", "custom_version_minor"=>"1", "comment"=>""}}, "commit"=>"Commit", "folder_id"=>"93", "id"=>"playground"}
  Current user: ... (id=...)
Completed 500 Internal Server Error in 13ms (ActiveRecord: 3.3ms)

NoMethodError (undefined method `strip' for nil:NilClass):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

```
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.2.1-p85 (2015-02-26) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_auto_percent           0.0.1
  redmine_base_deface            0.0.1
  redmine_ckeditor               1.1.2
  redmine_dmsf                   1.5.4
  redmine_local_avatars          1.0.0
  redmine_pastebin               0.2.0
  redmine_people                 1.0.0
  redmine_plugin_views_revisions 0.0.1
  redmine_revision_branches      0.3.0
  redmine_sudo                   0.0.1
  redmine_theme_changer          0.2.0
  redmine_wiki_extensions        0.7.0
  redmine_workflow_enhancements  0.5.0
  redmine_xls_export             0.2.1.t9
```

**Comment by morph027** [comment]
ok, got another copy of my vm which runs ```2.0.0-p598 (2014-11-13) [x86_64-linux]``` and it works there...

**Comment by morph027** [comment]
Won't work with ```ruby-2.0.0-p643``` too...

**Comment by picman** [comment]
But, in your system info I see *Ruby version                   2.2.1-p85 (2015-02-26) [x86_64-linux]* and not *ruby-2.0.0-pxxx*.
Anyway, there is no occurrence of calling the strip method in *DmsfUploadController*. Doesn't the log contain more information?

**Comment by morph027** [comment]
Jeah, this snippet is from the first occurance. I've changed to ```ruby-2.0.0-p598``` and everything works. I guess this is not really related to dmsf plugin...but somehow only occurs there.

Probably something changed in ActiveRecord in newer Ruby/Rails versions....I'll try to get some more debug messages.

**Comment by picman** [comment]
Probably solved in commit https://github.com/danmunn/redmine_dmsf/commit/53e7094097f295fd43002b5f66aa01c779327be4.
I've discovered that by some circumstances the plugin settings are not readable and as a consequence that error is raised. Then, it is necessary to go to the plugin settings, set the values again and save them.
