### ISSUE TITLE
NoMethodError on rake command

### ISSUE THREAD

**Issue by BagginsHasIt** [danmunn/redmine_dmsf#1050]
When updating Redmine to 4.0 and DMSF 2.4.1 I get a NoMethoderror when running the rake Command: 
 bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf RAILS_ENV="production"
Error:
NoMethodError: undefined method `to_prepare' for ActionDispatch::Reloader:Class

I updated both Redmine and DMSF at the same time before attempting to restart nginx.
If needed Ruby is version 2.4.6 and Rails is on 5.2.3

**Comment by picman** [comment]
Duplicates #932.

**Comment by BagginsHasIt** [comment]
I've installed gem activsupport but still get an error:
NoMethodError: undefined method `to_prepare' for ActionDispatch::Reloader:Class
after running command:
bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf RAILS_ENV="production"

**Comment by ahorek** [comment]
could you show us the whole exception?
`bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf RAILS_ENV=production --trace`

do you have any other plugins that might not compatible with redmine 4?
