### ISSUE TITLE
Fails since migration to Redmine 3.2

### ISSUE THREAD

**Issue by abhigginbotham** [danmunn/redmine_dmsf#515]
I just upgraded from 3.0 to 3.2 using a Bitnami VM.  I migrated the plugin and everything seemed to work but when I go to the configure for dmsf I get an error: Internal Error.  The same occurs if I click on a previously uploaded file from one of my project screens.  The production log shows this:

Started GET "/settings/plugin/redmine_dmsf" for 205.172.188.127 at 2016-03-09 16:08:23 +0000
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_dmsf"}
  Current user: ahigginbotham (id=3)
  Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_settings.html.erb (6.1ms)
  Rendered settings/plugin.html.erb within layouts/admin (9.2ms)
Completed 500 Internal Server Error in 27ms (ActiveRecord: 7.7ms)

ActionView::Template::Error (undefined method `strip' for nil:NilClass):
    53: <p>
    54:   <%=  content_tag(:label, "#{l(:label_file_storage_directory)}:") %>
    55:   <% 
    56:     storage_dir = @settings['dmsf_storage_directory'].strip
    57:     storage_dir = "#{Rails.root}/files/dmsf" if storage_dir.blank?
    58:   %>
    59:   <%= text_field_tag 'settings[dmsf_storage_directory]', storage_dir, :size => 50 %><br/>
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb__2164643138834309038_69852007269680'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb__2164643138834309038_69852007269680'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Please let me know how to fix this issue.

**Comment by EricOVGU** [comment]
Same here after upgrade to 3.2!

**Comment by picman** [comment]
Duplicates #494.
It has been already solved in v1.5.6.
Which version do you use?
Either upgrade to v1.5.6 or manually apply following code change: https://github.com/danmunn/redmine_dmsf/commit/53e7094097f295fd43002b5f66aa01c779327be4.

**Comment by abhigginbotham** [comment]
I downloaded (I thought) the latest stable version.  Here is my setup

Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.8-p440 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
  Cvs                            1.12.13
  Git                            2.6.1
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   1.5.3

It looks like I am a few versions behind.  I will try to find the latest, I applied the manual fix and it didn't solve it.

**Comment by picman** [comment]
Have you restated the web server after the code change?
Anyway, an upgrade to the latest stable v1.5.6 is highly recommended.

**Comment by abhigginbotham** [comment]
I did.  It kind of fixed a portion but not the uploading.  I had downloaded the latest but I guess in the migration I just copied the older plugin from my older redmine installation.  I'm going to do the upgrade.  One thing that isn't 100% clear is can I simply overwrite the directory and follow the install procedure or do I need to uninstall first?

**Comment by picman** [comment]
The best way is to replace the old folder. I mean to delete the previous one. No _uninstallation_ is needed.

**Comment by abhigginbotham** [comment]
I performed the update and now I get this:

Started GET "/projects/net-c/dmsf" for 205.172.188.127 at 2016-03-10 14:38:59 +0000
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"net-c"}
  Current user: ahigginbotham (id=3)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (1.3ms)
  Rendered attachments/_form.html.erb (4.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_multi_upload.html.erb (11.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (52.2ms)
Completed 200 OK in 185ms (Views: 79.0ms | ActiveRecord: 14.9ms)
Started POST "/projects/net-c/dmsf/upload/file" for 205.172.188.127 at 2016-03-10 14:39:14 +0000
Processing by DmsfUploadController#upload_file as */*
  Parameters: {"name"=>"Basic Architecture.xlsx", "authenticity_token"=>"GGQQ+b/8gIg8f8fgSjfYYbK28FpMVKqoC6hK7WEUmDmou4x/+Os9DsDkPBS7NILD/U7A+1xykjhSwlkzDo48XA==", "file"=>#<ActionDispatch::Http::UploadedFile:0x007fe895e2a6a0 @tempfile=#<Tempfile:/tmp/RackMultipart20160310-27898-6kk3f6.xlsx>, @original_filename="Basic Architecture.xlsx", @content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"Basic Architecture.xlsx\"\r\nContent-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\r\n">, "id"=>"net-c"}
  Current user: ahigginbotham (id=3)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload_file.html.erb (0.7ms)
Completed 200 OK in 34ms (Views: 8.2ms | ActiveRecord: 18.5ms)
Started POST "/projects/net-c/dmsf/upload/files" for 205.172.188.127 at 2016-03-10 14:39:14 +0000
Processing by DmsfUploadController#upload_files as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"81Hw8aPKYAzmDIAZLgZSumCUv++Uc0WAHzG+qVHnpBxDjmx35N3dihqXe+3fBQgYL2yPToRVfRBGW613Pn0AeQ==", "view_mode_o_1adgfer901isk1equ1jj59197ft1"=>"on", "o_1adgfer901isk1equ1jj59197ft1_count"=>"0", "uploaded"=>{"1"=>{"disk_filename"=>"160310143914_Basic_Architecture.xlsx", "content_type"=>"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "original_filename"=>"Basic Architecture.xlsx"}}, "id"=>"net-c"}
  Current user: ahigginbotham (id=3)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_upload_file.html.erb (8.6ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload_files.html.erb within layouts/base (13.0ms)
Completed 200 OK in 137ms (Views: 38.3ms | ActiveRecord: 58.1ms)
Started POST "/projects/net-c/dmsf/upload/commit" for 205.172.188.127 at 2016-03-10 14:39:16 +0000
Processing by DmsfUploadController#commit_files as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"ciI32KGkuwOXtM6CmCE38DszvZ8yUuieA23N+cusjvrC/ate5rMGhWsvNXZpIm1SdMuNPiJ00A5aB94npDYqnw==", "commited_files"=>{"1"=>{"disk_filename"=>"160310143914_Basic_Architecture.xlsx", "title"=>"Basic Architecture", "name"=>"Basic Architecture.xlsx", "description"=>"", "version"=>"1", "custom_version_major"=>"2", "custom_version_minor"=>"1", "comment"=>""}}, "commit"=>"Commit", "id"=>"net-c"}
  Current user: ahigginbotham (id=3)
Completed 500 Internal Server Error in 111ms (ActiveRecord: 55.5ms)

Errno::EACCES (Permission denied @ sys_fail2 - (/tmp/160310143914_Basic_Architecture.xlsx, /opt/bitnami/apps/redmine/htdocs/files/dmsf/p_net-c/160310143916_1_Basic_Architecture.xlsx)):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Looks to be a permissions issue with the /files/dmsf.  I did the step to set the www-data permissions in the instructions.  What should the permissions be on this directory?

**Comment by picman** [comment]
In general your web server user must have write access to /tmp and files/dmsf. So,:

```bash
chown -R www-data:www-data files/dmsf
```

**Comment by abhigginbotham** [comment]
I am still getting an error uploading.  I can open the config display and it tells me the 
File can't be created in storage directory

Here are my directory permissions
drwxr-xr-x 3 www-data www-data 4096 Mar  9 13:57 dmsf

I looked at the tmp directory and currently it is owned by bitnami:daemon.  I'm afraid to change that since I don't know what else that may break.

I don't remember having to set permissions on the tmp directory before here is the ls from it
/opt/bitnami/apps/redmine/htdocs$ ls -l tmp
total 28
drwxrwxr-x 3 bitnami daemon 4096 Mar  9 14:37 cache
drwxrwxr-x 2 bitnami daemon 4096 Mar  9 15:30 imports
drwxrwxr-x 2 bitnami daemon 4096 Feb  9 10:12 pdf
drwxrwxr-x 2 bitnami daemon 4096 Feb  9 10:11 sessions
drwxrwxr-x 2 bitnami daemon 4096 Feb  9 10:11 sockets
drwxrwxr-x 2 bitnami daemon 4096 Feb  9 10:12 test
drwxrwxr-x 2 bitnami daemon 4096 Feb  9 10:12 thumbnails

**Comment by abhigginbotham** [comment]
Ok.  I got it to work.  I needed to chmod the files directory and the dmsf directory to give write privileges.  It may be a little loose but for now I have a small team of 4 developers so it should be ok.

Here are the permissions:

drwxrwxrwx 3 www-data www-data 4096 Mar 10 15:37 dmsf

drwxr-xr-x  4 bitnami daemon 4096 Mar  9 13:57 files

I couldn't access the files directory originally from the command line the original permissions were
d-wx-wx--x  4 bitnami daemon 4096 Mar  9 13:57 files

If you suggest a tighter setting please provide.  I appreciate all the help in getting this working again.
