### ISSUE TITLE
Versioning via API

### ISSUE THREAD

**Issue by jasonpeate** [danmunn/redmine_dmsf#785]
I am unable to get the versioning feature to work via the API. Regardless of which way I try to change the version number

Here is a example of the xml I post to the server

`<attachments>
    <folder_id>8</folder_id>
    <uploaded_file>
        <disk_filename>0e403ce0-8450-4385-b7c2-3baff722a8f4.docx</disk_filename>
        <name>sdafasdfdasfdsa.docx</name>
        <title>Jason Testing Title 22222</title>
        <description>Jason Testing Description</description>
        <comment>Jason Testing Commit</comment>
        <version />
        <token>882.1227c0a4af3b3e96515b21eb942284560050ca187f94085a7eb2d509e2e8875b</token>
    </uploaded_file>
</attachments>`

I am unable to change the version number by any of the following tags aswell 

    <version>3</version>
    <custom_version_major>2</custom_version_major>
    <custom_version_minor>4</custom_version_minor>

**Comment by picman** [comment]
If I try it, I get the following error in `production.log`. I suppose that it's also your problem.

```ruby
[2017-10-17T13:09:06.291349 #7206]  INFO -- : Completed 500 Internal Server Error in 75ms (ActiveRecord: 14.0ms)
F, [2017-10-17T13:09:06.292528 #7206] FATAL -- : 
NoMethodError (undefined method `to_i' for ["3"]:Array
Did you mean?  to_s
               to_a
               to_h):
  plugins/redmine_dmsf/app/helpers/dmsf_upload_helper.rb:69:in `block in commit_files_internal'
```

**Comment by picman** [comment]
Fixed. Please update your code and try it again.

**Comment by jasonpeate** [comment]
After updating to 1.6 I am still getting the same problem. Please see attached screen shots and xml
![log](https://user-images.githubusercontent.com/10242334/31711664-cf968c70-b3f0-11e7-8036-e72f3b8947ae.PNG)
![redmine](https://user-images.githubusercontent.com/10242334/31711665-cfc32c6c-b3f0-11e7-94c2-2eb2e744e43f.PNG)

`<attachments>
    <folder_id />
    <uploaded_file>
        <disk_filename>0e403ce0-8450-4385-b7c2-3baff722a8f4.docx</disk_filename>
        <name>sdafasdfdasfdsa.docx</name>
        <title>Jason Testing Title 22222</title>
        <description>Jason Testing Description</description>
        <comment>Jason Testing Commit</comment>
        <version>4.5</version>
        <token>927.91c20a88ccd00f285a8907038435368da5852753f4232c624fd8647e50885a7c</token>
    </uploaded_file>
</attachments>`

**Comment by picman** [comment]
Your XML is wrong. Please see the wiki: https://github.com/danmunn/redmine_dmsf/wiki/REST-API

Your XML:
```xml
...
<version>4.5</version>
...
```
The right XML:
```xml
...
<version>3</version> <!-- It must be 3 (Custom version) -->
<custom_version_major>4</custom_version_major> <!-- Major version -->
<custom_version_minor>5</custom_version_minor> <!-- Minor version --> 
...
```

**Comment by jasonpeate** [comment]
So the change worked for the manual version, but the automated versioning is still not working 

XML

`<attachments>
    <folder_id />
    <uploaded_file>
        <disk_filename>0e403ce0-8450-4385-b7c2-3baff722a8f4.docx</disk_filename>
        <name>sdafasdfdasfdsa.docx</name>
        <title>Jason Testing Title 22222</title>
        <description>Jason Testing Description</description>
        <comment>Jason Testing Commit</comment>
        <version />
        <token>936.91c20a88ccd00f285a8907038435368da5852753f4232c624fd8647e50885a7c</token>
    </uploaded_file>
</attachments>`


![log](https://user-images.githubusercontent.com/10242334/31715558-4b2dbf7e-b3fc-11e7-9c19-6efaa20e1ca4.PNG)
![redmine](https://user-images.githubusercontent.com/10242334/31715560-4b58f14e-b3fc-11e7-9b7a-993bd5d51015.PNG)

**Comment by picman** [comment]
You're right. That's another bug. Fixed. Try it now, please.

**Comment by picman** [comment]
Fixed? Can we close this issue?

**Comment by jasonpeate** [comment]
Seems to be resolved
