### ISSUE TITLE
DMFS Version 2.4.1 is not working with redmine version 4.1.0

### ISSUE THREAD

**Issue by naveedkamran** [danmunn/redmine_dmsf#1071]
The plugin version **2.4.1** is not working with redmine version **4.1.0**. The stack trace is below:

```
Using redmine_extensions 0.2.16
Using redmine_github_hook 3.0.1 from source at `/usr/src/redmine/plugins/redmine_github_hook`
Using request_store 1.4.1
Using roadie 3.5.1
Using roadie-rails 2.1.0
Using rouge 3.12.0
Using ruby-ole 1.2.12.2
Using rubyzip 2.0.0
Using simple_enum 2.3.2
Using spreadsheet 0.6.9
Using uuidtools 2.1.5
Using vcard 0.2.16
Using wicked_pdf 1.1.0
Using wkhtmltopdf-binary 0.12.5
Using zip-zip 0.3
Bundle complete! 57 Gemfile dependencies, 80 gems now installed.
Gems in the groups development and test were not installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
rake aborted!
NoMethodError: undefined method `assets' for #<Rails::Engine::Configuration:0x00005623365bc070>
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/railtie/configuration.rb:97:in `method_missing'
/usr/local/bundle/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:20:in `<class:Engine>'
/usr/local/bundle/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:9:in `<module:RedmineExtensions>'
/usr/local/bundle/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:8:in `<top (required)>'
/usr/local/bundle/gems/redmine_extensions-0.2.16/lib/redmine_extensions.rb:1:in `require_relative'
/usr/local/bundle/gems/redmine_extensions-0.2.16/lib/redmine_extensions.rb:1:in `<top (required)>'
/usr/src/redmine/config/application.rb:18:in `<top (required)>'
/usr/src/redmine/Rakefile:5:in `<top (required)>'
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by tofi86** [comment]
Same here.

**Comment by picman** [comment]
Duplicates #1065.
