### ISSUE TITLE
500 Error when doing Approval Workflow related actions

### ISSUE THREAD

**Issue by nicupavel** [danmunn/redmine_dmsf#1260]
Every time I try to do an action like Approve on a document I get a 500 Internal Server error but refreshing I can see that the action did take place (ie the document is approved)

The logs show this:

```
redmine_1        | App 294044 output: I, [2021-06-01T11:58:26.850555 #294044]  INFO -- : Completed 500 Internal Server Error in 1080ms (ActiveRecord: 293.8ms)
redmine_1        | App 294044 output: F, [2021-06-01T11:58:26.851142 #294044] FATAL -- :
redmine_1        | App 294044 output: F, [2021-06-01T11:58:26.853910 #294044] FATAL -- : NoMethodError (undefined method `h' for #<DmsfWorkflowsController:0x00007f7d5a16d7b0>):
redmine_1        | App 294044 output: F, [2021-06-01T11:58:26.853967 #294044] FATAL -- :
redmine_1        | App 294044 output: F, [2021-06-01T11:58:26.853984 #294044] FATAL -- : plugins/redmine_dmsf/app/controllers/dmsf_workflows_controller.rb:167:in `block in new_action'
redmine_1        | App 294044 output: plugins/redmine_dmsf/app/controllers/dmsf_workflows_controller.rb:167:in `collect'
redmine_1        | App 294044 output: plugins/redmine_dmsf/app/controllers/dmsf_workflows_controller.rb:167:in `new_action'
redmine_1        | App 294044 output: lib/redmine/sudo_mode.rb:61:in `sudo_mode'
redmine_1        | App 294044 output: plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:56:in `call'

```

I'm not sure what is this related to.

**Comment by nicupavel** [comment]
When setting a new document revision and then use the 3 dots menu to do the assignment action the browser shows: 

`undefined method `owner=' for #1027 

But nothing on server logs. Action Assignment is performed and you can do Start action next successfully.
Approve action is successful but with in the reported error on server log and browser.  I have disabled everything related to
Notifications in DMSF configure.
In redmine DB/settings table: 

`dmsf_display_notified_recipients: ''`

**Comment by picman** [comment]
Add 1) Calling of the method h() is not needed here, you can safely remove it.
Add 2) It seems to me that you haven't run `redmine:plugins:migrate` task.

**Comment by nicupavel** [comment]
I ran the migrate task no change.
I commented out the h() method and no more errors.

**Comment by picman** [comment]
Check the database. There should be a new column `owner` in `dmsf_locks` table which is added by this migration: https://github.com/danmunn/redmine_dmsf/blob/master/db/migrate/20210115120901_add_owner_to_dmsf_lock.rb. Please check it.

```
mysql> desc dmsf_locks;
+----------------------------+--------------+------+-----+---------+----------------+
| Field                      | Type         | Null | Key | Default | Extra          |
+----------------------------+--------------+------+-----+---------+----------------+
| id                         | int          | NO   | PRI | NULL    | auto_increment |
| entity_id                  | int          | NO   | MUL | NULL    |                |
| user_id                    | int          | NO   |     | NULL    |                |
| created_at                 | datetime     | YES  |     | NULL    |                |
| updated_at                 | datetime     | YES  |     | NULL    |                |
| entity_type                | int          | NO   |     | NULL    |                |
| lock_type_cd               | int          | NO   |     | NULL    |                |
| lock_scope_cd              | int          | NO   |     | NULL    |                |
| uuid                       | varchar(36)  | YES  |     | NULL    |                |
| expires_at                 | datetime     | YES  |     | NULL    |                |
| dmsf_file_last_revision_id | int          | YES  |     | NULL    |                |
| owner                      | varchar(255) | YES  |     | NULL    |                |
+----------------------------+--------------+------+-----+---------+----------------+
```

**Comment by nicupavel** [comment]
Yes I have it:

```
mysql> desc dmsf_locks;
+----------------------------+--------------+------+-----+---------+----------------+
| Field                      | Type         | Null | Key | Default | Extra          |
+----------------------------+--------------+------+-----+---------+----------------+
| id                         | int(11)      | NO   | PRI | NULL    | auto_increment |
| entity_id                  | int(11)      | NO   | MUL | NULL    |                |
| user_id                    | int(11)      | NO   |     | NULL    |                |
| created_at                 | datetime     | NO   |     | NULL    |                |
| updated_at                 | datetime     | NO   |     | NULL    |                |
| entity_type                | int(11)      | NO   |     | NULL    |                |
| lock_type_cd               | int(11)      | NO   |     | NULL    |                |
| lock_scope_cd              | int(11)      | NO   |     | NULL    |                |
| uuid                       | varchar(36)  | YES  |     | NULL    |                |
| expires_at                 | datetime     | YES  |     | NULL    |                |
| dmsf_file_last_revision_id | int(11)      | YES  |     | NULL    |                |
| owner                      | varchar(255) | YES  |     | NULL    |                |
+----------------------------+--------------+------+-----+---------+----------------+
12 rows in set (0.01 sec)
```

**Comment by picman** [comment]
Please post a screen-shot with the error message from your browser and add corresponding log messages from the _production.log_.

**Comment by nicupavel** [comment]
I no longer have the error after removing references to h() method.
The 500 error is standard error
![redmine-error](https://user-images.githubusercontent.com/1650801/120464847-0d4bf000-c3a6-11eb-9fcb-69c1dff7b511.png)
The error on logs is as in first post.

**Comment by picman** [comment]
If there is no error in the production.log, there must be an error in error.log of the web server. Please check it and post it here.

**Comment by nicupavel** [comment]
I'm running under docker containers. The logs are for passenger and the error on that log:

```
App 121 output: I, [2021-06-01T23:50:17.086594 #121]  INFO -- : Completed 500 Internal Server Error in 2507ms (ActiveRecord: 233.7ms)
App 121 output: F, [2021-06-01T23:50:17.087194 #121] FATAL -- :   
App 121 output: F, [2021-06-01T23:50:17.089569 #121] FATAL -- : NoMethodError (undefined method `h' for #<DmsfWorkflowsController:0x00007f47091f7af0>):
App 121 output: F, [2021-06-01T23:50:17.089622 #121] FATAL -- :   
App 121 output: F, [2021-06-01T23:50:17.089651 #121] FATAL -- : plugins/redmine_dmsf/app/controllers/dmsf_workflows_controller.rb:167:in `block in new_action'
```

**Comment by picman** [comment]
Remove all occurrences of `h()` in _app/controllers_.

**Comment by martinbra** [comment]
I had the same issues and logs. With the current commit 86059ba at branch devel-2.4.8 the issue was resolved.

> 
> 
> Every time I try to do an action like Approve on a document I get a 500 Internal Server error but refreshing I can see that the action did take place (ie the document is approved)
> 
> The logs show this:
> 
> ```
> redmine_1        | App 294044 output: I, [2021-06-01T11:58:26.850555 #294044]  INFO -- : Completed 500 Internal Server Error in 1080ms (ActiveRecord: 293.8ms)
> redmine_1        | App 294044 output: F, [2021-06-01T11:58:26.851142 #294044] FATAL -- :
> redmine_1        | App 294044 output: F, [2021-06-01T11:58:26.853910 #294044] FATAL -- : NoMethodError (undefined method `h' for #<DmsfWorkflowsController:0x00007f7d5a16d7b0>):
> redmine_1        | App 294044 output: F, [2021-06-01T11:58:26.853967 #294044] FATAL -- :
> redmine_1        | App 294044 output: F, [2021-06-01T11:58:26.853984 #294044] FATAL -- : plugins/redmine_dmsf/app/controllers/dmsf_workflows_controller.rb:167:in `block in new_action'
> redmine_1        | App 294044 output: plugins/redmine_dmsf/app/controllers/dmsf_workflows_controller.rb:167:in `collect'
> redmine_1        | App 294044 output: plugins/redmine_dmsf/app/controllers/dmsf_workflows_controller.rb:167:in `new_action'
> redmine_1        | App 294044 output: lib/redmine/sudo_mode.rb:61:in `sudo_mode'
> redmine_1        | App 294044 output: plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:56:in `call'
> ```
> 
> I'm not sure what is this related to.

**Comment by paul-ri** [comment]
Sorry to chime in a closed ticket. We've had the issue too, even with 86059ba but I was struggling to get the logs.

It looks like there is still a reference to `h` [in here](https://github.com/danmunn/redmine_dmsf/commit/b687119d1dd3393b4e8f7679d4ee4db7245eec7d#diff-ddf626c80e15edc7078a441c0779fc34d6d7a02ec4208c4411950f8d4fcd61b5R226) introduced by b687119d1dd3393b4e8f7679d4ee4db7245eec7d.

```rb
to = recipients.collect{ |r| controller.__send__(:h, r.name) }.first(DMSF_MAX_NOTIFICATION_RECEIVERS_INFO).join(
```

Logs when running the plugin on `2.4.8 devel`:
```
I, [2021-06-10T14:51:15.823279 #6]  INFO -- : Started GET "/dmsf_workflows/5/start?dmsf_file_revision_id=2423" for 31.111.113.179 at 2021-06-10 14:51:15 +0000 
I, [2021-06-10T14:51:15.824113 #6]  INFO -- : Processing by DmsfWorkflowsController#start as HTML 
I, [2021-06-10T14:51:15.824145 #6]  INFO -- :   Parameters: {"dmsf_file_revision_id"=>"2423", "id"=>"5"} 
I, [2021-06-10T14:51:15.836577 #6]  INFO -- :   Current user: paulriou (id=62) 
I, [2021-06-10T14:51:16.514597 #6]  INFO -- :   Rendering plugins/redmine_dmsf/app/views/dmsf_mailer/workflow_notification.text.erb within layouts/mailer 
I, [2021-06-10T14:51:16.517994 #6]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/workflow_notification.text.erb within layouts/mailer (3.3ms) 
I, [2021-06-10T14:51:16.525378 #6]  INFO -- :   Rendering plugins/redmine_dmsf/app/views/dmsf_mailer/workflow_notification.html.erb within layouts/mailer 
I, [2021-06-10T14:51:16.526155 #6]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/workflow_notification.html.erb within layouts/mailer (0.7ms) 
I, [2021-06-10T14:51:20.738156 #6]  INFO -- : Completed 500 Internal Server Error in 4914ms (ActiveRecord: 375.2ms) 
F, [2021-06-10T14:51:20.738677 #6] FATAL -- :    
F, [2021-06-10T14:51:20.740665 #6] FATAL -- : NoMethodError (undefined method `h' for #<DmsfWorkflowsController:0x00007f3250b12248>): 
F, [2021-06-10T14:51:20.740688 #6] FATAL -- :    
F, [2021-06-10T14:51:20.740703 #6] FATAL : plugins/redmine_dmsf/app/models/dmsf_workflow.rb:226:in `block in notify_users' 
plugins/redmine_dmsf/app/models/dmsf_workflow.rb:226:in `collect' 
plugins/redmine_dmsf/app/models/dmsf_-- workflow.rb:226:in `notify_users' 
plugins/redmine_dmsf/app/controllers/dmsf_workflows_controller.rb:419:in `start' 
lib/redmine/sudo_mode.rb:61:in `sudo_mode' 
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:56:in `call' 
```

versions:

```
Environment:
  Redmine version                4.2.1.stable
  Ruby version                   2.7.3-p183 (2021-04-05) [x86_64-linux]
  Rails version                  5.2.5
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.4
  Mercurial                      4.8.2
  Bazaar                         2.8.0
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  mdu-redmine-macros             0.3.1
  redmine_dmsf                   2.4.8 devel
  redmine_mermaid_macro          1.0.0
```

Is there something I am missing regarding what that commit assumes about h() being present or not? If you could give some hints about what's this function maybe I can continue looking into it.

& thanks for the plugin by the way!

**Comment by picman** [comment]
Fixed.

**Comment by paul-ri** [comment]
Thank you so much!

I confirm it fixed it for us
